--------------------------------------------------------------------------------
-- SCHEMA OFICIAL DA PLATAFORMA DE CURSOS "PROGRAMA CERTO" (SUPABASE)
--------------------------------------------------------------------------------

-- 1. Tabela: usuarios
CREATE TABLE IF NOT EXISTS public.usuarios (
    id TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    papel TEXT DEFAULT 'aluno',
    data_do_cadastro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tabela: perfis
CREATE TABLE IF NOT EXISTS public.perfis (
    id TEXT PRIMARY KEY,
    id_do_usuario TEXT,
    cargo TEXT,
    foto_perfil_url TEXT,
    redes_sociais TEXT
);

-- 3. Tabela: cursos
CREATE TABLE IF NOT EXISTS public.cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_do_curso TEXT NOT NULL,
    descricao TEXT,
    aulas INT DEFAULT 0,
    categoria TEXT,
    instrutor TEXT,
    gradient_color TEXT
);

-- 4. Tabela: modulos
CREATE TABLE IF NOT EXISTS public.modulos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_do_curso BIGINT,
    titulo_do_modulo TEXT NOT NULL,
    ordem INT DEFAULT 1,
    posicao_apos_aula INT
);

-- 5. Tabela: aulas_dos_cursos
CREATE TABLE IF NOT EXISTS public.aulas_dos_cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_do_curso BIGINT,
    id_do_modulo BIGINT,
    numero_da_aula INT,
    aula INT,
    nome_da_aula TEXT NOT NULL,
    conteudo TEXT,
    nome_do_teste TEXT,
    alternativa_a TEXT,
    alternativa_b TEXT,
    alternativa_c TEXT,
    alternativa_d TEXT,
    alternativa_certa TEXT
);

-- 6. Tabela: projetos_cursos
CREATE TABLE IF NOT EXISTS public.projetos_cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_do_curso BIGINT,
    nome_do_projeto TEXT NOT NULL
);

-- 7. Tabela: projetos_progresso
CREATE TABLE IF NOT EXISTS public.projetos_progresso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_do_projeto BIGINT NOT NULL,
    id_do_usuario TEXT,
    status TEXT DEFAULT 'Não iniciado',
    id_epc TEXT
);

-- 8. Tabela: avaliacoes
CREATE TABLE IF NOT EXISTS public.avaliacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_do_curso BIGINT,
    nome_da_avaliacao TEXT NOT NULL,
    questoes_e_gabarito TEXT
);

-- 9. Tabela: avaliacoes_concluidas
CREATE TABLE IF NOT EXISTS public.avaliacoes_concluidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_do_usuario TEXT NOT NULL,
    id_da_avaliacao BIGINT NOT NULL,
    nota NUMERIC,
    data_da_conclusao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 10. Tabela: atividades_concluidas
CREATE TABLE IF NOT EXISTS public.atividades_concluidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_do_usuario TEXT NOT NULL,
    id_da_aula BIGINT NOT NULL,
    data_da_conclusao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 11. Tabela: cursos_concluidos
CREATE TABLE IF NOT EXISTS public.cursos_concluidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_do_usuario TEXT NOT NULL,
    id_do_curso BIGINT NOT NULL,
    data_da_conclusao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- =======================================================
-- ATIVAÇÃO DE RLS E CRIAÇÃO DAS POLÍTICAS DE PERMISSÃO TOTAL
-- =======================================================

DO $$ 
DECLARE 
    tbl TEXT;
    t_list TEXT[] := ARRAY[
        'usuarios', 'perfis', 'cursos', 'modulos', 
        'aulas_dos_cursos', 'projetos_cursos', 'projetos_progresso', 
        'avaliacoes', 'avaliacoes_concluidas', 'atividades_concluidas', 
        'cursos_concluidos'
    ];
BEGIN
    FOREACH tbl IN ARRAY t_list LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Acesso total publico e autenticado %I" ON public.%I;', tbl, tbl);
        EXECUTE format('
            CREATE POLICY "Acesso total publico e autenticado %I" 
            ON public.%I 
            FOR ALL 
            USING (true) 
            WITH CHECK (true);
        ', tbl, tbl);
    END LOOP;
END $$;


-- Garante a existência de colunas em tabelas pré-existentes no Supabase
ALTER TABLE public.aulas_dos_cursos ADD COLUMN IF NOT EXISTS numero_da_aula INT;
ALTER TABLE public.aulas_dos_cursos ADD COLUMN IF NOT EXISTS aula INT;
ALTER TABLE public.aulas_dos_cursos ADD COLUMN IF NOT EXISTS id_do_modulo BIGINT;
ALTER TABLE public.projetos_cursos DROP COLUMN IF EXISTS id_do_usuario;
ALTER TABLE public.projetos_cursos DROP COLUMN IF EXISTS id_usuario;


--------------------------------------------------------------------------------
-- EXEMPLO DE INSERÇÃO: 1 CURSO, 2 MÓDULOS E 3 AULAS
--------------------------------------------------------------------------------

DO $$ 
DECLARE 
    v_curso_id BIGINT;
    v_modulo1_id BIGINT;
    v_modulo2_id BIGINT;
BEGIN
    -- 1. Criar o Curso
    INSERT INTO public.cursos (nome_do_curso, descricao, aulas, categoria, instrutor, gradient_color)
    VALUES (
        'Curso de Projetos Práticos',
        'Curso prático sobre desenvolvimento, organização e envio de projetos na plataforma.',
        3,
        'Programação',
        'Instrutor da Plataforma',
        '#ADD8E6, #000084'
    )
    RETURNING id INTO v_curso_id;

    -- 2. Criar os 2 Módulos
    INSERT INTO public.modulos (id_do_curso, titulo_do_modulo, ordem)
    VALUES (v_curso_id, 'Módulo 1: Preparação do Projeto', 1)
    RETURNING id INTO v_modulo1_id;

    INSERT INTO public.modulos (id_do_curso, titulo_do_modulo, ordem)
    VALUES (v_curso_id, 'Módulo 2: Entrega e Envio', 2)
    RETURNING id INTO v_modulo2_id;

    -- 3. Criar as 3 Aulas
    -- Módulo 1 (2 Aulas)
    INSERT INTO public.aulas_dos_cursos (id_do_curso, id_do_modulo, numero_da_aula, aula, nome_da_aula, conteudo)
    VALUES (
        v_curso_id,
        v_modulo1_id,
        1,
        1,
        'Meu projeto',
        '# Meu projeto' || E'\n\n' || 'Nesta aula você aprenderá a estruturar a ideia inicial e a configuração básica do seu projeto.'
    );

    INSERT INTO public.aulas_dos_cursos (id_do_curso, id_do_modulo, numero_da_aula, aula, nome_da_aula, conteudo)
    VALUES (
        v_curso_id,
        v_modulo1_id,
        2,
        2,
        'Introdução ao Conteúdo',
        '# Introdução ao Conteúdo' || E'\n\n' || 'Nesta aula abordaremos os conceitos essenciais e o desenvolvimento do conteúdo principal do projeto.'
    );

    -- Módulo 2 (1 Aula)
    INSERT INTO public.aulas_dos_cursos (id_do_curso, id_do_modulo, numero_da_aula, aula, nome_da_aula, conteudo)
    VALUES (
        v_curso_id,
        v_modulo2_id,
        3,
        3,
        'Enviar projeto',
        '# Enviar projeto' || E'\n\n' || 'Nesta aula você verá os passos finais para revisar, compilar e enviar seu projeto concluído.'
    );

    -- 4. Criar o Projeto do Curso (projetos_cursos)
    INSERT INTO public.projetos_cursos (id_do_curso, nome_do_projeto)
    VALUES (v_curso_id, 'Projeto Prático do Curso');

END $$;

